Feature/ot289 22
alkemyTech/OT289-client pull request #8
Opened 2022-09-15 16:12 UTC by Ignamaldonado

https://alkemy-labs.atlassian.net/browse/OT289-22

Finished the header and made it responsive, with dynamic links coming from the data folder and a logo coming from the public folder.

![uARxynfyFf](https://user-images.githubusercontent.com/95056116/190454168-c60df2cd-46c3-4061-903e-e3310831ed2a.png)
![ie2PGUJ8us](https://user-images.githubusercontent.com/95056116/190454280-e8170af7-d30b-4600-b921-8735cc0f78b9.png)
![rsA6A1WltV](https://user-images.githubusercontent.com/95056116/190454392-54d69103-bccd-4d2d-9edb-801290ebd344.png)

2022-09-16 12:58 UTC, GauntStrelok commented on src/components/Header/Header.js
> +        {headerLinks.map(button => <Link to={button}><button key={button}>{button}</button></Link>)}
Que pasa si quiero que el texto del boton sea diferente del link? como lo haria?

2022-09-20 05:16 UTC, GauntStrelok commented on src/components/Header/Header.js
> +        {headerLinks.map((button,index) => index === 0 ? <Link to='/' key={button}><button key={button}  className='home-button'>{button}</button></Link> : <Link to={button} key={button}><button key=
Esto no esta muy bueno, no se te ocurre una mejor forma de hacerlo mas que de preguntar si es el primer boton?

Alguno forma que tambien podamos ponerle diferente nombre al boton que a la ruta que te lleva?

2022-09-20 11:41 UTC, Ignamaldonado commented on src/components/Header/Header.js
> +        {headerLinks.map((button,index) => index === 0 ? <Link to='/' key={button}><button key={button}  className='home-button'>{button}</button></Link> : <Link to={button} key={button}><button key=
Se me ocurre darle el link a la home al logo y eliminar inicio de la botonera

2022-09-21 11:16 UTC, GauntStrelok requested changes
Fijate lo de la key, y hace un pull de main para arreglar conflictos

2022-09-21 11:16 UTC, GauntStrelok commented on src/components/Header/Header.js
> +        {headerLinks.map((button) => <Link to={button.link} key={button.name}><button key={button.name}>{button.name}</button></Link> )}
Preferiria que la key no tuviera espacios, como si lo podria tener el nombre de un boton

2022-09-21 11:16 UTC, GauntStrelok commented on src/data/headerLinks.js
> +export const headerLinks = [{
simple no? :P
Lo bueno de esto, es que desde aca ya le podes seguir agregando cosas, digamos que queres agregarle el color de fondo del boton, es solo agregarle una propiedad a este objeto :)

2022-09-21 11:58 UTC, Ignamaldonado commented on src/components/Header/Header.js
> +        {headerLinks.map((button) => <Link to={button.link} key={button.name}><button key={button.name}>{button.name}</button></Link> )}
le paso el index entonces a la key para que sea unica sin espacio, sino tambien podria pasar el link ya que no puede tener espacios

2022-09-22 04:33 UTC, GauntStrelok commented on src/components/Header/Header.js
> +        {headerLinks.map((button) => <Link to={button.link} key={button.name}><button key={button.name}>{button.name}</button></Link> )}
el link esta bueno, mas que el index :)

2022-09-22 04:33 UTC, GauntStrelok commented
Hacer tambien pull de main para arreglar conflictosd

2022-09-27 21:40 UTC, merged